### ISSUE TITLE
Errors in the master version of MediaWiki

### ISSUE THREAD

**Issue by danielyepezgarces** [litespeedtech/lscache_mediawiki#10]
Some things changed in MediaWiki since version MW 1.41 and that is why the extension does not work at the moment
```
[8c79a5dd03f4abb6a4811e68] /wiki/Special:LiteSpeedCache Error: Call to undefined method MediaWiki\User\User::getGroups()

Backtrace:

from /www/mediawiki/w/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(162)
#0 /www/mediawiki/w/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(34): SpecialLiteSpeedCache->isSysAdmin()
#1 /www/mediawiki/w/includes/specialpage/SpecialPage.php(719): SpecialLiteSpeedCache->execute()
#2 /www/mediawiki/w/includes/specialpage/SpecialPageFactory.php(1693): MediaWiki\SpecialPage\SpecialPage->run()
#3 /www/mediawiki/w/includes/actions/ActionEntryPoint.php(502): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /www/mediawiki/w/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#5 /www/mediawiki/w/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#6 /www/mediawiki/w/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#7 {main}

```

**Comment by WuhuaChen** [comment]
hi,

this problem was fixed in submit https://github.com/litespeedtech/lscache_mediawiki/commit/030a9dcf31a93e8b7c7b678e5b4b4bc8bc8bcd63

thanks.

**Comment by keepersdungeon** [comment]
> Some things changed in MediaWiki since version MW 1.41 and that is why the extension does not work at the moment
> 
> ```
> [8c79a5dd03f4abb6a4811e68] /wiki/Special:LiteSpeedCache Error: Call to undefined method MediaWiki\User\User::getGroups()
> 
> Backtrace:
> 
> from /www/mediawiki/w/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(162)
> #0 /www/mediawiki/w/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(34): SpecialLiteSpeedCache->isSysAdmin()
> #1 /www/mediawiki/w/includes/specialpage/SpecialPage.php(719): SpecialLiteSpeedCache->execute()
> #2 /www/mediawiki/w/includes/specialpage/SpecialPageFactory.php(1693): MediaWiki\SpecialPage\SpecialPage->run()
> #3 /www/mediawiki/w/includes/actions/ActionEntryPoint.php(502): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
> #4 /www/mediawiki/w/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
> #5 /www/mediawiki/w/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
> #6 /www/mediawiki/w/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
> #7 {main}
> ```

were u able to make it work?
Thanks
