### ISSUE TITLE
Call to undefined method OutputPage::addWikiText

### ISSUE THREAD

**Issue by pawan-in** [litespeedtech/lscache_mediawiki#4]
I just installed the master version of this extension to my MediaWiki site running on 1.34 and when I am visiting the Special page to activate I'm seeing the following issue. 

/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php: Call to undefined method OutputPage::addWikiText()

Backtrace:

#0 /extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(64): SpecialLiteSpeedCache->showView(boolean)
#1 /includes/specialpage/SpecialPage.php(575): SpecialLiteSpeedCache->execute(NULL)
#2 /includes/specialpage/SpecialPageFactory.php(611): SpecialPage->run(NULL)
#3 /includes/MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#4 /includes/MediaWiki.php(900): MediaWiki->performRequest()
#5 /includes/MediaWiki.php(527): MediaWiki->main()
#6 /index.php(44): MediaWiki->run()
#7 {main}

**Comment by pawan-in** [comment]
@WuhuaChen @litespeedtech Can you guys please take a look at this issue? Thank you
