### ISSUE TITLE
MW 1.41

### ISSUE THREAD

**Issue by keepersdungeon** [litespeedtech/lscache_mediawiki#9]
Hello,
Does the Extension work with Mediawiki 1.41?

Thank you

**Comment by WuhuaChen** [comment]
hi,

it works with Mediawiki 1.42 , thanks.

**Comment by keepersdungeon** [comment]
Alright thanks, but not on 1.41 just gave it another try with latest.

**Comment by WuhuaChen** [comment]
I just tested it works on 1.41, but you need download the latest source:  https://github.com/litespeedtech/lscache_mediawiki/archive/refs/heads/master.zip

**Comment by keepersdungeon** [comment]
I tried again with the link but I'm getting same thing this error

`MediaWiki is unable to load the extension LiteSpeedCache. Please check that the extension's name is correct and all of its files are properly installed.

Details:
Error reading /PATH TO WIKI/wiki/extensions/LiteSpeedCache/extension.json. filemtime(): stat failed for /PATH TO WIKI/wiki/extensions/LiteSpeedCache/extension.json.

#0 /PATH TO WIKI/wiki/includes/GlobalFunctions.php(54): ExtensionRegistry->queue()
#1 /PATH TO WIKI/wiki/LocalSettings.php(340): wfLoadExtension()
#2 /PATH TO WIKI/wiki/includes/Setup.php(212): require_once('/PATH TO WIKI/')
#3 /PATH TO WIKI/wiki/includes/WebStart.php(92): require_once('/PATH TO WIKI/')
#4 /PATH TO WIKI/wiki/index.php(44): require('/PATH TO WIKI/')
#5 {main}`

**Comment by keepersdungeon** [comment]
When I go to Special:LiteSpeedCache

[db1dcfd1799d9494c9c4958d] /Special:LiteSpeedCache TypeError: MediaWiki\User\UserGroupManager::getUserGroups(): Argument #1 ($user) must be of type MediaWiki\User\UserIdentity, null given, called in '/PATH TO WIKI/wiki/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php on line 164

Backtrace:

from /PATH TO WIKI/wiki/includes/user/UserGroupManager.php(728)
#0 /PATH TO WIKI/wiki/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(164): MediaWiki\User\UserGroupManager->getUserGroups()
#1 /PATH TO WIKI/wiki/extensions/LiteSpeedCache/SpecialLiteSpeedCache.php(36): SpecialLiteSpeedCache->isSysAdmin()
#2 /PATH TO WIKI/wiki/includes/specialpage/SpecialPage.php(728): SpecialLiteSpeedCache->execute()
#3 /PATH TO WIKI/wiki/includes/specialpage/SpecialPageFactory.php(1621): MediaWiki\SpecialPage\SpecialPage->run()
#4 /PATH TO WIKI/wiki/includes/MediaWiki.php(357): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#5 /PATH TO WIKI/wiki/includes/MediaWiki.php(960): MediaWiki->performRequest()
#6 /PATH TO WIKI/wiki/includes/MediaWiki.php(613): MediaWiki->main()
#7 /PATH TO WIKI/wiki/index.php(50): MediaWiki->run()
#8 /PATH TO WIKI/wiki/index.php(46): wfIndexMain()
#9 {main}

**Comment by keepersdungeon** [comment]
and same thing with 1.42 I upgraded and got the same error
